code --install-extension akamud.vscode-theme-onedark
code --install-extension akamud.vscode-theme-onelight
code --install-extension Angular.ng-template
code --install-extension Arjun.swagger-viewer
code --install-extension bierner.markdown-preview-github-styles
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension Equinusocio.vsc-material-theme
code --install-extension karigari.chat
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension octref.vetur
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension Tyriar.sort-lines
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
